KnowledgeManage/Models/Result_Lesson.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace KnowledgeManage.Models
{
    //codebydangkhai
    public class Result_Lesson
    {
        public string nameLesson { get; set; }
        public string linkLesson { get; set; }
        public string nameRel_Lesson { get; set; }
        public string linkRel_Lesson { get; set; }
        public string nameConcept { get; set; }
        public string linkConcept { get; set; }

        public string nameConstruct { get; set; }
        public string linkConstruct { get; set; }

        public string nameOperator { get; set; }
        public string linkOperator { get; set; }

        public string nameExercise { get; set; }
        public string linkExercise { get; set; }
    }
}

KnowledgeManage/Controllers/DS_and_AController.cs
using KnowledgeManage.Data;
using KnowledgeManage.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace KnowledgeManage.Controllers
{
    public class DS_and_AController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DS_and_AController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Menu()
        {
            return View();
        }
        public IActionResult Content()
        {
            return View(Relate("ContentView"));
        }
        public IActionResult Search()
        {
            return View(Relate("SearchView"));
        }

        /*Tìm kiếm chủ đề bài học*/
        public async Task<IActionResult> SearchLesson(string searchString)
        {
                ViewData["ss"] = searchString;
            var les = from l in _context.Lesson
                      where l.Key_Lesson.ToLower().Contains(searchString.ToLower())
                      select l;
            return View("Result_lesson", await les.ToListAsync());
        }

        public async Task<IActionResult> Result_lesson()
        {
            return View(await _context.Lesson.ToListAsync());
        }

        /*Tìm kiếm bài tập*/
        public async Task<IActionResult> SearchExercise(string searchString)
        {
            ViewData["ss"] = searchString;
            var les = from l in _context.Lesson
                      where l.Key_Lesson.ToLower().Contains(searchString.ToLower())
                      select l;

            var ans = from item in _context.Exercise
                      from l in les
                      where item.LessonId_Lesson.Equals(l.Id_Lesson)
                      select item;
            return View("Result_exercise", await ans.ToListAsync());
        }
        public async Task<IActionResult> Result_exercise()
        {
            return View(await _context.Exercise.ToListAsync());
        }


        /*Tìm kiếm khái niệm*/
        public async Task<IActionResult> SearchConcept(string searchString)
        {
            ViewData["ss"] = searchString;
            var les = from l in _context.Lesson
                      where l.Key_Lesson.ToLower().Contains(searchString.ToLower())
                      select l;

            var ans = from item in _context.Concept
                      from l in les
                      where item.LessonId_Lesson.Equals(l.Id_Lesson)
                      select item;
            return View("Result_concept", await ans.ToListAsync());
        }
        public async Task<IActionResult> Result_concept()
        {
            return View(await _context.Concept.ToListAsync());
        }

        /*Tìm kiếm cách biểu diễn/ cài đặt*/
        public async Task<IActionResult> SearchConstruct(string searchString)
        {
            ViewData["ss"] = searchString;
            var les = from l in _context.Lesson
                      where l.Key_Lesson.ToLower().Contains(searchString.ToLower())
                      select l;

            var ans = from item in _context.Construct
                      from l in les
                      where item.LessonId_Lesson.Equals(l.Id_Lesson)
                      select item;
            return View("Result_construct", await ans.ToListAsync());
        }
        public async Task<IActionResult> Result_construct()
        {
            return View(await _context.Construct.ToListAsync());
        }

        /*Tìm kiếm toán tử*/
        public async Task<IActionResult> SearchOperator(string searchString)
        {
            ViewData["ss"] = searchString;
            var les = from l in _context.Lesson
                      where l.Key_Lesson.ToLower().Contains(searchString.ToLower())
                      select l;

            var ans = from item in _context.Operator
                           from l in les
                           where item.LessonId_Lesson.Equals(l.Id_Lesson)
                           select item;
            return View("Result_operator", await ans.ToListAsync());

        }
        public async Task<IActionResult> Result_operator()
        {
            return View(await _context.Operator.ToListAsync());
        }

        public IActionResult Result_Multy(string searchString)
        {
            ViewData["ss"] = searchString;
            return View(Result_Something(searchString));
        }

        public List<Result_Lesson> Result_Something(string searchString)
        {
            Result_Lesson reles = new Result_Lesson() { };
            var les = from l in _context.Lesson
                      where l.Key_Lesson.ToLower().Contains(searchString.ToLower())
                      select new
                      {
                          l.Name_Lesson,
                          l.Id_Lesson
                      };

            var les_conc = from cc in _context.Concept
                           from l in les
                           where cc.LessonId_Lesson.Equals(l.Id_Lesson)
                           select new
                           {
                               l.Name_Lesson,
                               l.Id_Lesson,
                               cc.Name_Concept,
                               cc.Link_Concept
                           };

            var les_cons = from cs in _context.Construct
                           from l in les
                           where cs.LessonId_Lesson.Equals(l.Id_Lesson)
                           select new
                           {
                               l.Name_Lesson,
                               l.Id_Lesson,
                               cs.Name_Construct,
                               cs.Link_Construct
                           };

            var les_oper = from op in _context.Operator
                           from l in les
                           where op.LessonId_Lesson.Equals(l.Id_Lesson)
                           select new
                           {
                               l.Name_Lesson,
                               l.Id_Lesson,
                               op.Name_Operator,
                               op.Link_Operator
                           };

            var les_exer = from ex in _context.Exercise
                           from l in les
                           where ex.LessonId_Lesson.Equals(l.Id_Lesson)
                           select new
                           {
                               l.Name_Lesson,
                               l.Id_Lesson,
                               ex.Name_Exercise,
                               ex.Link_Exercise
                           };

            //Construct join in Concept-Lesson
            var leftjoin1 = from lcc in les_conc
                            join lcs in les_cons
                            on lcc.Id_Lesson equals lcs.Id_Lesson into left_1
                            from l_1 in left_1.DefaultIfEmpty()
                            select new
                            {
                                lcc.Name_Lesson,
                                lcc.Id_Lesson,

                                lcc.Name_Concept,
                                lcc.Link_Concept,

                                l_1.Name_Construct,
                                l_1.Link_Construct
                            };

            //Opperator join in leftjoin1
            var leftjoin2 = from left_1 in leftjoin1
                            join loper in les_oper
                            on left_1.Id_Lesson equals loper.Id_Lesson into left_2
                            from l_2 in left_2.DefaultIfEmpty()
                            select new
                            {
                                left_1.Name_Lesson,
                                left_1.Id_Lesson,

                                left_1.Name_Concept,
                                left_1.Link_Concept,

                                left_1.Name_Construct,
                                left_1.Link_Construct,

                                l_2.Name_Operator,
                                l_2.Link_Operator
                            };

            //Exercise join in leftjoin2
            var leftjoin3 = from left_2 in leftjoin2
                            join lexer in les_exer
                            on left_2.Id_Lesson equals lexer.Id_Lesson into left_3
                            from l_3 in left_3.DefaultIfEmpty()
                            select new
                            {
                                left_2.Name_Lesson,
                                left_2.Id_Lesson,

                                left_2.Name_Concept,
                                left_2.Link_Concept,

                                left_2.Name_Construct,
                                left_2.Link_Construct,

                                left_2.Name_Operator,
                                left_2.Link_Operator,

                                l_3.Name_Exercise,
                                l_3.Link_Exercise
                            };
            var result = from all in leftjoin3
                         select new Result_Lesson()
                         {
                             nameLesson = all.Name_Lesson,
                             linkLesson = all.Id_Lesson,

                             nameConcept = all.Name_Concept,
                             linkConcept = all.Link_Concept,

                             nameConstruct = all.Name_Construct,
                             linkConstruct = all.Link_Construct,

                             nameOperator = all.Name_Operator,
                             linkOperator = all.Link_Operator,

                             nameExercise = all.Name_Exercise,
                             linkExercise = all.Link_Exercise
                         };

KnowledgeManage/Views/DS_and_A/I.cshtml
@{
    ViewData["Title"] = "I";
    Layout = "~/Views/DS_and_A/Menu.cshtml";
}



<div style="padding-left: 15%; padding-right: 15%; ">
    <div id="I_1" >
        <h1>CẤU TRÚC DỮ LIỆU (DATA STRUCTURE)</h1>
        <h3>Khái niệm</h3>
            <p>Cấu trúc dữ liệu là cách lưu trữ, tổ chức dữ liệu có thứ tự, có hệ thống để dữ liệu có thể được sử dụng một cách hiệu quả. </p>
    </div>
    <hr />
    <h3>Thuật ngữ cơ bản</h3>
    <ul>
        <li><p><b>Dữ liệu</b>: Các giá trị hoặc là tập hợp các giá trị.</p></li>
        <li><p><b>Phần tử dữ liệu</b>: Một đơn vị đơn lẻ của giá trị.</p></li>
        <li><p><b>Các phần tử nhóm</b>: Phần tử dữ liệu mà được chia thành các phần tử con thì được gọi là các phần tử nhóm.</p></li>
        <li><p><b>Các phần tử cơ bản</b>: Phần tử dữ liệu mà không thể bị chia nhỏ thành các phần tử con thì gọi là các phần tử cơ bản.</p></li>
        <li><p><b>Thuộc tính và Thực thể</b>: Một thực thể chứa một vài thuộc tính và các thuộc tính đó có thể được gán các giá trị.</p></li>
        <li><p><b>Tập hợp thực thể</b>: Các thực thể mà có các thuộc tính tương tự nhau thì cấu thành một tập hợp thực thể.</p></li>
        <li><p><b>Trường</b>: Một đơn vị thông tin cơ bản biểu diễn một thuộc tính của một thực thể.</p></li>
        <li><p><b>Bản ghi</b>: Một tập hợp các giá trị trường của một thực thể đã cho.</p></li>
        <li><p><b>File</b>: Một tập hợp các bản ghi của các thực thể trong một tập hợp thực thể đã cho.</p></li>
    </ul>
    <hr />
    <h3>
        Các cấu trúc dữ liệu thường gặp:
    </h3>
    <ul>

        <li><a href="I_2">Cấu trúc dữ liệu mảng (array)</a></li>
        <li><a href="I_3">Cấu trúc dữ liệu danh sách liên kết (Linked list)</a></li>
        <li><a href="I_4">Cấu trúc dữ liệu ngăn xếp (Stack)</a></li>
        <li><a href="I_5">Cấu trúc dữ liệu hàng đợi (Queue)</a></li>
        <li><a href="I_6">Cấu trúc dữ liệu cây (Tree)</a></li>
        <li><a href="I_7">Cấu trúc dữ liệu đồ thị (Graph)</a></li>
    </ul>
</div>
<div>
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
</div>

KnowledgeManage/Views/DS_and_A/III_11.cshtml
@{
    ViewData["Title"] = "III_11";
    Layout = "~/Views/DS_and_A/Menu.cshtml";
}

<style>
    img {
        display: inline-block;
        max-width: 100%;
        max-height: 100%;
        display: block;
        margin: 0 auto;
        text-align: center;
    }
</style>
<div id="accordion" style="padding-left: 15%; padding-right: 15%; ">
    <h1>BÀI TẬP VỀ GIẢI THUẬT ĐỆ QUY</h1>
    <p class="alert-warning">BẠN CÓ THỂ NHẤN VÀO ĐỂ XEM BÀI GIẢI</p>
    <div id="kinhdien">
        <h3>Các bài toán kinh điển</h3>
        <div class="card" id="fibonacy">
            <div class="card-header">
                <a class="card-link" data-toggle="collapse" href="#Bai1">
                    Bài 1. Dãy Fibonacy
                </a>
            </div>
            <div id="Bai1" class="collapse container" data-parent="#accordion">
                <br />
                <u><b>Mô tả bài toán</b></u>
                <p>Dãy Fibonacci là dãy vô hạn các số tự nhiên bắt đầu bằng hai phần tử 1 và 1, các phần tử sau đó được thiết lập theo quy tắc mỗi phần tử luôn bằng tổng hai phần tử trước nó.</p>
                <u><b>Ý tưởng bài toán</b></u>
                <p>- Điều kiện dừng là n == 1 hoặc n == 2 thì sẽ trả về là 1. Do hai phần tử đầu là 1.</p>
                <p>- Hàm sẽ gọi dần số fibonacy thứ n về số fibonacy thứ 1 và 2: fibonacy(n) = fibonacy(n-1) + fibonacy(n-2).</p>
                <u><b>Bài giải:</b></u>
                <pre style="overflow: auto; font-family:Consolas" class="card-body">
<code>
#include &lt;iostream&gt;

using namespace std;

int fibonacy (int n){
    if (n==1 || n == 2)
        return  1;
    return fibonacy(n-1) + fibonacy(n-2);
}

int main()
{
    cout << fibonacy(30); // kết quả = 832040

    return 0;
}
</code> 
</pre>
            </div>
        </div>
        <div class="card" id="giaithua">
            <div class="card-header">
                <a class="card-link" data-toggle="collapse" href="#Bai2">
                    Bài 2. Tính giai thừa
                </a>
            </div>
            <div id="Bai2" class="collapse container" data-parent="#accordion">
                <br />
                <u><b>Mô tả bài toán</b></u>
                <p>Giai thừa là một toán tử một ngôi trên tập hợp các số tự nhiên. Cho n là một số tự nhiên dương,"<i>n giai thừa</i>", ký hiệu <i>n!</i> là tích của <i>n</i> số tự nhiên dương đầu tiên.</p>
                <p>n! = 1*2*3*...*n <i>(1)</i></p>
                <p>n! = (n-1)!*n <i>(2)</i></p>
                <u><b>Ý tưởng bài toán</b></u>
                <p>Từ <i>(2)</i>, ta có thể xây dựng hàm tính giai thừa bằng đệ quy như sau:</p>
                <p>- Điều kiện dừng là n == 1 sẽ trả về 1 (vì 1! = 1)</p>
                <p>- Trường hợp đệ quy tiến đến điều kiện dừng là n! = (n-1)!*n</p>
                <u><b>Bài giải:</b></u>
                <pre style="overflow: auto; font-family:Consolas" class="card-body">
<code>
#include &lt;iostream&gt;

using namespace std;

int giaithua (int n){
    if (n==1)
        return  1;
    return giaithua(n-1)*n;
}

int main()
{
    cout << giaithua(6); // kết quả = 720

    return 0;
}
</code> 
</pre>
            </div>
        </div>
        <div class="card" id="thaphanoi">
            <div class="card-header">
                <a class="card-link" data-toggle="collapse" href="#Bai3">
                    Bài 3. Bài toán tháp Hà Nội
                </a>
            </div>
            <div id="Bai3" class="collapse container" data-parent="#accordion">
                <br />
                <u><b>Mô tả bài toán</b></u>
                <p>Bài toán tháp Hà Nội ( Tower of Hà Nội ) là một trò chơi toán học gồm 3 cột và số đĩa nhiều hơn 1. </p>
                <img src="~/Image/thaphanoi.jpg" />
                <p>Với quy tắc các đĩa nhỏ phải nằm trên các đĩa lớn. Nhiệm vụ của trò chơi là di chuyển các đĩa có kích cỡ khác nhau sang cột khác sao cho vẫn đảm bảo thứ tự ban đầu của các đĩa: đĩa nhỏ nằm trên đĩa lớn. </p>
                <img src="~/Image/thap-ha-noi.gif" />
                <u><b>Ý tưởng bài toán</b></u>
                <p>Qui ước: Đặt tên 3 cột là A B C để tiện theo dõi. Yêu cầu bài toán là chuyển n chiếc đĩa từ cột A sang cột C</p>
                <p>Thực hiện các bước:</p>
                <ul>
                    <li>Đầu tiên ta lấy cột C làm cọc trung gian. Chuyển n-1 chiếc đĩa từ cột A sang cột B.</li>
                    <li>Ta chuyển chiếc đĩa lớn nhất sang cột C</li>
                    <li>Lấy cột A làm cột trung gian chuyển n-1 chiếc đĩa từ cột B sang cột C</li>
                </ul>
                <ul></ul>
                <u><b>Bài giải:</b></u>
                <pre style="overflow: auto; font-family:Consolas" class="card-body">
<code>
#include &lt;iostream&gt;

using namespace std;

void HaNoiTower(int n , char a, char b, char c ){
    if(n==1){
        cout << "\t" << a << "-------" << c << endl;
        return;
    }
    HaNoiTower(n-1,a,c,b);
    HaNoiTower(1,a,b,c);
    HaNoiTower(n-1,b,a,c);
}
int main(){
    char a='A', b='B', c='C';
    int n;
    cout << "Nhap n: ";
    cin >> n;
    HaNoiTower(n,a,b,c);
}
</code> 
</pre>
            </div>
        </div>
    </div>
    <div id="cacdangdequy">
        <h3>Các bài toán về các dạng đệ quy</h3>
        <h5>Đệ quy tuyến tính (Linear Recursion)</h5>
        <p>Mỗi lần thực thi chỉ gọi đệ quy một lần</p>
        <div class="card" id="linear">
            <div class="card-header">
                <a class="card-link" data-toggle="collapse" href="#Bai3">
                    Bài 1. Hàm tính giai thừa
                </a>
            </div>
            <div id="Bai3" class="collapse container" data-parent="#accordion">
                <u><b>Bài giải:</b></u>
                <pre style="overflow: auto; font-family:Consolas" class="card-body">
<code>
int factorial(int n)
{
    if (n == 0)
        return 1;
    else
        return n * factorial(n - 1); // Linear Recursion
}
</code> 
</pre>
            </div>
        </div>
        <br />
        <h5>Đệ quy nhị phân (Binary Recursion)</h5>
        <p>Mỗi lần thực thi có thể gọi đệ quy 2 lần</p>
        <div class="card" id="binary">
            <div class="card-header">
                <a class="card-link" data-toggle="collapse" href="#Bai4">
                    Bài 2. Tính tổ hợp chập K của N bằng đệ quy
                </a>
            </div>
            <div id="Bai4" class="collapse container" data-parent="#accordion">
                <u><b>Bài giải:</b></u>
                <pre style="overflow: auto; font-family:Consolas" class="card-body">
<code>
int combine(int n, int k)
{
    if (k == 0 || k == n)
        return 1;
    else
        return combine(n - 1, k) + combine(n - 1, k - 1); // Binary Recursion
}
</code> 
</pre>
            </div>
        </div>
        <br />
        <h5>Đệ quy lồng (Nested Recursions)</h5>
        <p>Tham số trong lời gọi đệ quy là một lời gọi đệ quy, đệ quy lồng chiếm bộ nhớ rất nhanh.</p>
        <div class="card" id="nested">
            <div class="card-header">
                <a class="card-link" data-toggle="collapse" href="#Bai5">
                    Bài 3. Viết hàm Ackermann
                </a>
            </div>
            <div id="Bai5" class="collapse container" data-parent="#accordion">
                <br />
                <u><b>Ý tưởng bài toán</b></u>
                <p>Ta có các tính chất của hàm Ackerman sau, cho hàm A(m, n) là hàm ackerman:</p>
                <ul>
                    <li>- Nếu m = 0, thì A(m, n) = n+1</li>
                    <li>- Nếu n = 0, thì A(m, n) = A(m - 1, 1)</li>
                    <li>- Trường hợp còn lại, A(m, n) = A(m - 1, A(m, n - 1))</li>
                </ul>
                <u><b>Bài giải:</b></u>
                <pre style="overflow: auto; font-family:Consolas" class="card-body">
<code>
int ackerman(int m, int n)
{
    if (m == 0)
        return (n + 1);
    else
        if (n == 0)
            return ackerman(m - 1, 1);
        else
            return ackerman(m - 1, ackerman(m, n - 1)); // Nested Recursion
}
</code> 
</pre>
            </div>
        </div>
        <br />
        <h5>Đệ quy hỗ tương (Mutual Recursion)</h5>
        <p>Các hàm gọi đệ quy lẫn nhau</p>
        <div class="card" id="mutual">
            <div class="card-header">
                <a class="card-link" data-toggle="collapse" href="#Bai6">
                    Bài 4. Xét tính chẵn lẻ của một số nguyên dương bằng đệ quy
                </a>
            </div>
            <div id="Bai6" class="collapse container" data-parent="#accordion">
                <u><b>Bài giải:</b></u>
                <pre style="overflow: auto; font-family:Consolas" class="card-body">
<code>
bool isEven(unsigned int n) 
{
    if (n == 0)
        return true;
    else
        return isOdd(n - 1);
}

bool isOdd(unsigned int n) 
{
    if (n == 1)
        return true;
    else
        return isEven(n - 1);
}
</code> 
</pre>
            </div>
        </div>
        <br />
    </div>
</div>
<div>
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
</div>

KnowledgeManage/Views/DS_and_A/II_3_3.cshtml
@{
    ViewData["Title"] = "II_3_3";
    Layout = "~/Views/DS_and_A/Menu.cshtml";
}

<style>
    img {
        display: inline-block;
        max-width: 100%;
        max-height: 100%;
        display: block;
        margin: 0 auto;
        text-align: center;
    }
</style>

<div style="padding-left: 15%; padding-right: 15%; ">
    <div id="II_3_3">
        <h3>GIẢI THUẬT SẮP XẾP CHỌN (SELECTION SORT)</h3>
        <div id="II_3_3_1">
            <h5>Khái niệm giải thuật sắp xếp chọn</h5>
            <p>Thuật toán sắp xếp chọn sẽ sắp xếp một mảng bằng cách đi tìm phần tử có giá trị nhỏ nhất(giả sử với sắp xếp mảng tăng dần) trong đoạn đoạn chưa được sắp xếp và đổi cho phần tử nhỏ nhất đó với phần tử ở đầu đoạn chưa được sắp xếp(không phải đầu mảng). Thuật toán sẽ chia mảng làm 2 mảng con: một mảng con đã được sắp xếp. một mảng con chưa được sắp xếp. Tại mỗi bước lặp của thuật toán, phần tử nhỏ nhất ở mảng con chưa được sắp xếp sẽ được di chuyển về đoạn đã sắp xếp.</p>
            <img src="~/Image/selection-sort.gif" />
        </div>
        <hr />
        <div id="II_3_3_2">
            <h5>Xây dựng giải thuật sắp xếp chọn</h5>
            <p>Ý tưởng cho giải thuật sắp xếp chèn được trình bày thành các bước như sau:</p>
            <div class="card" style="background-color: #F1F1F1">
                <p>Giả sử ta có mảng a có n phần tử</p>
                <ul>
                    <li><b>Bước 1: </b>Thiết lập min về vị trí 0</li>
                    <li><b>Bước 2: </b>Tìm kiếm phần tử nhỏ nhất trong danh sách</li>
                    <li><b>Bước 3: </b>Tráo đổi với giá trị tại vị trí min</li>
                    <li><b>Bước 4: </b>Tăng min lên để chỉ vị trí phấn tử kế tiếp</li>
                    <li><b>Bước 5: </b>Lặp lại cho đến khi hết danh sách</li>
                </ul>
            </div><br />
            <hr />
            <p>Giải thuật mẫu cho sắp xếp chọn</p>
            <div class="card" style="background-color: #F1F1F1">
<pre style="padding: 1em; margin: .5em 0; overflow: auto;" class="card-body">
<code>
Bắt đầu giải thuật sắp xếp chọn (Selection Sort) 
    list  : mảng các phần tử
    n     : kích cỡ mảng

    <span style="color: #008">for</span> i = 1 tới n - 1
        /* thiết lập phần tử hiện tại là min*/
        min = i    
  
        /* kiểm tra phần tử có là nhỏ nhất không */

        <span style="color: #008">for</span> j = i+1 tới n 
            <span style="color: #008">if</span> list[j] < list[min] thì
                min = j;
            kết thúc if
        kết thúc for

        /* tráo đổi phần tử nhỏ nhất với phần tử hiện tại*/
        <span style="color: #008">if</span> indexMin != i  then
            tráo đổi list[min] và list[i]
        kết thúc if

    kết thúc for
	
Kết thúc giải thuật
</code> </pre>
            </div><br />
            <hr />
            <p><b>Ví dụ: </b>Thủ tục sắp xếp chọn trên một mảng các số nguyên được viết bằng C như sau:</p>
            <div class="card" style="background-color: #F1F1F1">
<pre style="padding: 1em; margin: .5em 0; overflow: auto;" class="card-body">
<code>
void selectionSort(int a[], int n){
    int i, j, min_idx;
    // Di chuyển ranh giới của mảng đã sắp xếp và chưa sắp xếp
    for (i = 0; i < n-1; i++){
    // Tìm phần tử nhỏ nhất trong mảng chưa sắp xếp
        min_idx = i;
        for (j = i+1; j < n; j++)
            if (a[j] < a[min_idx])
                min_idx = j;
 
    // Đổi chỗ phần tử nhỏ nhất với phần tử đầu tiên
        int t = a[min_idx];
        a[min_idx] = a[i];
        a[i] = t;
    }
}
</code> </pre>
            </div><br />
            <p>Giải thuật này không phù hợp với tập dữ liệu lớn khi mà độ phức tạp trường hợp xấu nhất và trường hợp trung bình là O(n<sup>2</sup>) với n là số phần tử.</p>
        </div>
    </div>
    <div>
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
    </div>
</div>

KnowledgeManage/Views/DS_and_A/Result_lesson.cshtml
@model IEnumerable<KnowledgeManage.Models.Lesson>
@{
    ViewData["Title"] = "Result_test";
}


<div style="height: 100vh; background-color: #F5F5F5; overflow-y: auto; overflow-x:hidden; font-size: 16px; padding-left: 15%; padding-right: 15%; text-indent: 5%;" class=" flex-fill">
    <h1 style="text-align:center">CÁC KIẾN THỨC CHO TỪ KHÓA "<span class="text-success">@ViewData["ss"]</span>"</h1>

    @if (Model.Count() > 0)
    {
        <table class="table table-hover table-bordered">
            <thead style="position: sticky;top: 0" class="thead-light">
                <tr>
                    <th>
                        <p>Tên bài học</p>
                    </th>

                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name_Lesson)
                        </td>
                        <td>
                            <a href="@item.Id_Lesson">Details</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

        <div>
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
        </div>
    }
    else
    {
        <br />
        <br />
        <br />
        <p style="text-align:center">
            <b>KHÔNG THẤY KẾT QUẢ TÌM KIẾM CHO "<span class="text-danger">@ViewData["ss"]</span>"!!!!</b>
        </p>
    }
    <div>
        <a asp-controller="DS_and_A" asp-action="Search">Trở về trang tìm kiếm</a>
    </div>
</div>